## Scientific Computing 2021: Homework Assignment 2 
Due Monday October 18, 2021 (23:59)

### Problem 1 (2 points)
Let $A_q=\left(\begin{matrix}1 & q\\ 0 & 1\end{matrix}\right)$ with $q\in\mathbb R$. 
* For any $q$, find condition number $\kappa(A_q)$ with respect to the $l^2$-norm.
* Give an example of specific values of $q,\mathbf b, \Delta\mathbf b$ such that, when solving $A_q\mathbf x = \mathbf b$ and $A_q(\mathbf x+\Delta \mathbf x)=\mathbf b +\Delta\mathbf b$, we get 

$$\frac{\|\Delta \mathbf x\|}{\|\mathbf x\|}\ge 10^6\frac{\|\Delta\mathbf b\|}{\|\mathbf b\|}.$$

If $\|\cdot\|$ is the $l^2$-norm and $A_q$ is arbitrary, then $$\kappa(A_q)=\sqrt{\frac{\lambda_{\max}(A_q^*A_q)}{\lambda_{\min}(A_q^*A_q)}}$$

$$A_q^* A_q = \left(\begin{matrix}1 & q\\ q & 1 + q^2\end{matrix}\right)$$

Eigenvals:
$$\begin{vmatrix} 1 - \lambda & q \\ q & 1 + q^2 - \lambda \end{vmatrix} = \lambda^2 - \lambda(q^2 + 2) + 1 = 0$$

$$\lambda_{1, 2} = \frac{\pm q\sqrt{q^2 + 4} + q^2 + 2}{2} \in \mathbb R$$

$$\kappa(A_q) = \sqrt{\frac{\lambda_\max}{\lambda_\min}} = \sqrt{\frac{|q|\sqrt{q^2 + 4} + q^2 + 2}{-|q|\sqrt{q^2 + 4} + q^2 + 2}} = \frac{|q|\sqrt{q^2 + 4} + q^2 + 2}{\sqrt{(q^2 + 2)^2 - q^2(q^2 + 4)}} = \frac{|q|\sqrt{q^2 + 4} + q^2 + 2}{2}$$

$$\left(\begin{matrix}1 & q \\ 0 & 1\end{matrix}\right) \left(\begin{matrix}x_1 \\ x_2 \end{matrix}\right) = \left(\begin{matrix}b_1 \\ b_2 \end{matrix}\right)$$

$$\left\{\begin{eqnarray} x_1 + q\,x_2 & = & b_1 \\ x_2 & = & b_2 \end{eqnarray}\right.$$

$$\left\{\begin{eqnarray} x_1 & = & b_1 - q\,b_2 \\ x_2 & = & b_2 \end{eqnarray}\right.$$

In [64]:
numSteps = 10
qv = np.linspace(-100, 100, num=numSteps)
b1v = np.linspace(-10, 10, num=numSteps)
b2v = np.linspace(-10, 10, num=numSteps)
db1v = np.linspace(-10, 10, num=numSteps)
db2v = np.linspace(-10, 10, num=numSteps)

In [65]:
for q in qv:
    for b1 in b1v:
        for b2 in b2v:
            for db1 in db1v:
                for db2 in db2v:
                    if (
    (db1 - q * db2)**2 + db2**2
) / (
    (b1 - q * b2)**2 + b2**2
) >= 10**6 * (db1**2 + db2**2) / (b1**2 + b2**2):
                        print(q, b1, b2, db1, db2)

In [69]:
def relErr(v, dv):
    return np.linalg.norm(dv) / np.linalg.norm(v)


def solve(q, b):
    return np.array([b[0] - q * b[1], b[1]])

In [86]:
db = np.array([10, 0])
b = np.array([10000000001, 1000])
q = 10000000

x = solve(q, b)
dx = solve(q, b + db) - x

left = relErr(x, dx)
right = 10**6 * relErr(b, db)
print(left, right)
print(left >= right, left / right)

0.00999999500000375 0.000999999999899995
True 9.9999950010038


In [87]:
x, dx, x + dx

(array([   1, 1000], dtype=int64),
 array([10,  0], dtype=int64),
 array([  11, 1000], dtype=int64))

### Problem 2 (2 points)
* Write a program to compute an approximate value for the derivative of a function using the finite-difference formula 

  $$f'(x)\approx \frac{f(x+h)-f(x)}{h}.$$

  Test your program using the function $\tan(x)$ at $x=1$. Determine the error by comparing with the value obtained using the analytic derivative. Plot the magnitude of the error as a function of $h$, for $h=10^{-k}, k=0,\ldots,16$. You should use log scale for $h$ and for the magnitude of the error. What is the minimum value of the error and at which $h$ is it achieved? Explain this result theoretically.
* Repeat the exercise using the centered difference approximation

 $$f'(x)\approx \frac{f(x+h)-f(x-h)}{2h}.$$

 What is now different and why?

### Problem 3 (2 points)
* Implement regularized regression with an adaptive choice of regularization parameter. Your algorithm must accept the training data (`Xtrain`, `Ytrain`) and the input part of test data (`Xtest`), and output a prediction for test data (`Ypred`). You may use standard linear algebra libraries, but not specialized predictive modeling software (e.g., `scikit-learn`). Your algorithm should choose the regularization parameter by some optimization over a reasonable range of values and may use a sub-division of the training data into a train-in-train and a test-in-train components.
* Test your algorithm on real data from UCI repository:
  * https://archive.ics.uci.edu/ml/datasets/Relative+location+of+CT+slices+on+axial+axis
  * https://archive.ics.uci.edu/ml/datasets/Physicochemical+Properties+of+Protein+Tertiary+Structure
  
  Use random subsets of 300 rows as training sets, and the remaining rows as the test sets. Use the relative RMS error as the measure of accuracy.
  Compare your results with results of some linear models implemented in standard predictive modeling software    (e.g., `Ridge` and `LinearRegression` from `scikit-learn`).

### Problem 4 (2 points)
Suppose that we use the Leapfrog algorithm with some $\Delta t$ to simulate the dynamics of the harmonic oscillator (https://en.wikipedia.org/wiki/Harmonic_oscillator) with positive mass $m$ and force constant $k$ (in other words, with the energy function $H=\frac{m\dot x^2}{2}+\frac{kx^2}{2}$). Assuming a perfect implementation of Leapfrog, at which combinations of $\Delta t, m, k$ will the simulation diverge as $n\to\infty$, in the sense that $\sup_n(\tilde x_n^2+\tilde v_{n+1/2}^2)=\infty$?

### Problem 5 (2 points)
Consider the velocity Verlet method for solving the equation $\frac{d}{dt}{x\choose v}={v\choose f_1(x)}$: 

\begin{align}
\tilde v_{n+1/2} &= \tilde v_{n}+\frac{1}{2}f_1(\tilde x_n)\Delta t\\
\tilde x_{n+1} &= \tilde x_{n}+\tilde v_{n+1/2}\Delta t\\
\tilde v_{n+1} &= \tilde v_{n+1/2}+\frac{1}{2}f_1(\tilde x_{n+1})\Delta t
\end{align}
Find its global convergence order and verify it experimentally.