In [2]:
from numpy import array
from numpy import hstack
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import RepeatVector
from tensorflow.keras.layers import TimeDistributed
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
  X, y = list(), list()
  for i in range(len(sequences)):
    # find the end of this pattern
    end_ix = i + n_steps_in
    out_end_ix = end_ix + n_steps_out
    # check if we are beyond the dataset
    if out_end_ix > len(sequences):
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)
 
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# define model
model = Sequential()
model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=0)
# demonstrate prediction
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[[ 89.94639   95.8818   185.19104 ]
  [100.64042  105.280495 206.63083 ]]]


In [14]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
out_seq2 = 2*array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
out_seq2 = out_seq2.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq, out_seq2))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 1
# covert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)

In [15]:
dataset

array([[ 10,  15,  25,  50],
       [ 20,  25,  45,  90],
       [ 30,  35,  65, 130],
       [ 40,  45,  85, 170],
       [ 50,  55, 105, 210],
       [ 60,  65, 125, 250],
       [ 70,  75, 145, 290],
       [ 80,  85, 165, 330],
       [ 90,  95, 185, 370]])

In [16]:
X

array([[[ 10,  15,  25,  50],
        [ 20,  25,  45,  90],
        [ 30,  35,  65, 130]],

       [[ 20,  25,  45,  90],
        [ 30,  35,  65, 130],
        [ 40,  45,  85, 170]],

       [[ 30,  35,  65, 130],
        [ 40,  45,  85, 170],
        [ 50,  55, 105, 210]],

       [[ 40,  45,  85, 170],
        [ 50,  55, 105, 210],
        [ 60,  65, 125, 250]],

       [[ 50,  55, 105, 210],
        [ 60,  65, 125, 250],
        [ 70,  75, 145, 290]],

       [[ 60,  65, 125, 250],
        [ 70,  75, 145, 290],
        [ 80,  85, 165, 330]]])

In [17]:
y

array([[[ 40,  45,  85, 170]],

       [[ 50,  55, 105, 210]],

       [[ 60,  65, 125, 250]],

       [[ 70,  75, 145, 290]],

       [[ 80,  85, 165, 330]],

       [[ 90,  95, 185, 370]]])

In [19]:
import numpy as np

In [21]:
np.load("D:\\DOCS\\Git\\scientific_computing\\final_project\\grid_search_resultslook_back_5_activation_relu_learning_rate0.001.npy")

array([[0.49388233, 0.5038084 ],
       [0.49890658, 0.558236  ],
       [0.54292774, 0.51761687],
       ...,
       [0.5041978 , 0.52948534],
       [0.50447017, 0.52981913],
       [0.5042349 , 0.52967906]], dtype=float32)